/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BoosterInventory = IDL.Record({
  'alignmentCount' : IDL.Nat,
  'bombCount' : IDL.Nat,
  'nextFruitChangeCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AudioMetadata = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Badges = IDL.Record({
  'hasRookie' : IDL.Bool,
  'hasAdvanced' : IDL.Bool,
  'hasNovice' : IDL.Bool,
  'hasMaster' : IDL.Bool,
});
export const Badge = IDL.Record({ 'name' : IDL.Text, 'design' : IDL.Text });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'badges' : Badges,
});
export const LeaderboardEntry = IDL.Record({
  'month' : IDL.Nat,
  'score' : IDL.Nat,
});
export const Time = IDL.Int;
export const HealthCheckLog = IDL.Record({
  'status' : IDL.Text,
  'recoveryAttempted' : IDL.Bool,
  'recoverySuccess' : IDL.Bool,
  'timestamp' : Time,
});
export const BoosterType = IDL.Variant({
  'bomb' : IDL.Null,
  'nextFruitChange' : IDL.Null,
  'alignment' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminLogout' : IDL.Func([], [], []),
  'adminUpdateUserBoosters' : IDL.Func([IDL.Text, BoosterInventory], [], []),
  'appStatus' : IDL.Func(
      [],
      [IDL.Variant({ 'healthy' : IDL.Null })],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'audioFilesEmpty' : IDL.Func([], [IDL.Bool], ['query']),
  'banUser' : IDL.Func([IDL.Text], [], []),
  'checkDailyLogin' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
  'deleteOwnAccount' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'doesUserExist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getAllAudioMetadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, AudioMetadata))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Record({
              'soundPreference' : IDL.Bool,
              'badges' : Badges,
              'highScore' : IDL.Nat,
              'isBanned' : IDL.Bool,
              'avatarId' : IDL.Text,
              'boosters' : BoosterInventory,
            }),
          )
        ),
      ],
      ['query'],
    ),
  'getAudioMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AudioMetadata)],
      ['query'],
    ),
  'getAvatar' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getBadge' : IDL.Func([IDL.Text], [IDL.Opt(Badge)], ['query']),
  'getBoosterInventory' : IDL.Func([IDL.Text], [BoosterInventory], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompleteLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, LeaderboardEntry))],
      ['query'],
    ),
  'getHealthCheckLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, HealthCheckLog))],
      ['query'],
    ),
  'getHighScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getRank' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getSoundPreference' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getTopPlayers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserTheme' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getWinCounts' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'logout' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetLeaderboard' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'unbanUser' : IDL.Func([IDL.Text], [], []),
  'updateAvatar' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateBoosterCount' : IDL.Func([IDL.Text, BoosterType, IDL.Nat], [], []),
  'updateSoundPreference' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateUserTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadAllAudioFiles' : IDL.Func([], [], []),
  'uploadAudioFromUrl' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'useBooster' : IDL.Func([IDL.Text, BoosterType, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BoosterInventory = IDL.Record({
    'alignmentCount' : IDL.Nat,
    'bombCount' : IDL.Nat,
    'nextFruitChangeCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AudioMetadata = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Badges = IDL.Record({
    'hasRookie' : IDL.Bool,
    'hasAdvanced' : IDL.Bool,
    'hasNovice' : IDL.Bool,
    'hasMaster' : IDL.Bool,
  });
  const Badge = IDL.Record({ 'name' : IDL.Text, 'design' : IDL.Text });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'badges' : Badges });
  const LeaderboardEntry = IDL.Record({ 'month' : IDL.Nat, 'score' : IDL.Nat });
  const Time = IDL.Int;
  const HealthCheckLog = IDL.Record({
    'status' : IDL.Text,
    'recoveryAttempted' : IDL.Bool,
    'recoverySuccess' : IDL.Bool,
    'timestamp' : Time,
  });
  const BoosterType = IDL.Variant({
    'bomb' : IDL.Null,
    'nextFruitChange' : IDL.Null,
    'alignment' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminLogout' : IDL.Func([], [], []),
    'adminUpdateUserBoosters' : IDL.Func([IDL.Text, BoosterInventory], [], []),
    'appStatus' : IDL.Func(
        [],
        [IDL.Variant({ 'healthy' : IDL.Null })],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'audioFilesEmpty' : IDL.Func([], [IDL.Bool], ['query']),
    'banUser' : IDL.Func([IDL.Text], [], []),
    'checkDailyLogin' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
    'deleteOwnAccount' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'doesUserExist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getAllAudioMetadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, AudioMetadata))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Record({
                'soundPreference' : IDL.Bool,
                'badges' : Badges,
                'highScore' : IDL.Nat,
                'isBanned' : IDL.Bool,
                'avatarId' : IDL.Text,
                'boosters' : BoosterInventory,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'getAudioMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AudioMetadata)],
        ['query'],
      ),
    'getAvatar' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getBadge' : IDL.Func([IDL.Text], [IDL.Opt(Badge)], ['query']),
    'getBoosterInventory' : IDL.Func([IDL.Text], [BoosterInventory], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompleteLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, LeaderboardEntry))],
        ['query'],
      ),
    'getHealthCheckLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, HealthCheckLog))],
        ['query'],
      ),
    'getHighScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getRank' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getSoundPreference' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getTopPlayers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserTheme' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getWinCounts' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'logout' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetLeaderboard' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'unbanUser' : IDL.Func([IDL.Text], [], []),
    'updateAvatar' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateBoosterCount' : IDL.Func([IDL.Text, BoosterType, IDL.Nat], [], []),
    'updateSoundPreference' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateUserTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadAllAudioFiles' : IDL.Func([], [], []),
    'uploadAudioFromUrl' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'useBooster' : IDL.Func([IDL.Text, BoosterType, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };