/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'description' : string,
}
export interface Badge { 'name' : string, 'design' : string }
export interface Badges {
  'hasRookie' : boolean,
  'hasAdvanced' : boolean,
  'hasNovice' : boolean,
  'hasMaster' : boolean,
}
export interface BoosterInventory {
  'alignmentCount' : bigint,
  'bombCount' : bigint,
  'nextFruitChangeCount' : bigint,
}
export type BoosterType = { 'bomb' : null } |
  { 'nextFruitChange' : null } |
  { 'alignment' : null };
export type ExternalBlob = Uint8Array;
export interface HealthCheckLog {
  'status' : string,
  'recoveryAttempted' : boolean,
  'recoverySuccess' : boolean,
  'timestamp' : Time,
}
export interface LeaderboardEntry { 'month' : bigint, 'score' : bigint }
export type Time = bigint;
export interface UserProfile { 'username' : string, 'badges' : Badges }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string, string], undefined>,
  'adminLogout' : ActorMethod<[], undefined>,
  'adminUpdateUserBoosters' : ActorMethod<
    [string, BoosterInventory],
    undefined
  >,
  'appStatus' : ActorMethod<[], { 'healthy' : null }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'audioFilesEmpty' : ActorMethod<[], boolean>,
  'deleteAudioFile' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'doesUserExist' : ActorMethod<[string], boolean>,
  'getAllAudioMetadata' : ActorMethod<[], Array<[string, AudioMetadata]>>,
  'getAllUsers' : ActorMethod<
    [],
    Array<
      [
        string,
        {
          'soundPreference' : boolean,
          'badges' : Badges,
          'boosters' : BoosterInventory,
        },
      ]
    >
  >,
  'getAudioMetadata' : ActorMethod<[string], [] | [AudioMetadata]>,
  'getBadge' : ActorMethod<[string], [] | [Badge]>,
  'getBoosterInventory' : ActorMethod<[string], BoosterInventory>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompleteLeaderboard' : ActorMethod<[], Array<[string, LeaderboardEntry]>>,
  'getHealthCheckLogs' : ActorMethod<[], Array<[Time, HealthCheckLog]>>,
  'getRank' : ActorMethod<[string], bigint>,
  'getSoundPreference' : ActorMethod<[string], boolean>,
  'getTopPlayers' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserTheme' : ActorMethod<[string], string>,
  'getWinCounts' : ActorMethod<[string], bigint>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], undefined>,
  'logout' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'resetLeaderboard' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitScore' : ActorMethod<[string, bigint], undefined>,
  'updateBoosterCount' : ActorMethod<[string, BoosterType, bigint], undefined>,
  'updateSoundPreference' : ActorMethod<[string, boolean], undefined>,
  'updateUserTheme' : ActorMethod<[string, string], undefined>,
  'uploadAllAudioFiles' : ActorMethod<[], undefined>,
  'uploadAudioFromUrl' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'useBooster' : ActorMethod<[string, BoosterType, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];